//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertProfiler.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlertApproval {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlertApproval() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlertProfiler.WebApp.Resources.AlertApproval", typeof(AlertApproval).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string ACCOUNT_NUMBER {
            get {
                return ResourceManager.GetString("ACCOUNT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ACTION {
            get {
                return ResourceManager.GetString("ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Page.
        /// </summary>
        public static string APPROVAL_PAGE {
            get {
                return ResourceManager.GetString("APPROVAL_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status.
        /// </summary>
        public static string APPROVAL_STATUS {
            get {
                return ResourceManager.GetString("APPROVAL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string APPROVE {
            get {
                return ResourceManager.GetString("APPROVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string APPROVED {
            get {
                return ResourceManager.GetString("APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Id.
        /// </summary>
        public static string COUNTRY_ID {
            get {
                return ResourceManager.GetString("COUNTRY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CREATED_BY {
            get {
                return ResourceManager.GetString("CREATED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string DATE_CREATED {
            get {
                return ResourceManager.GetString("DATE_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisApprove.
        /// </summary>
        public static string DISAPPROVE {
            get {
                return ResourceManager.GetString("DISAPPROVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisApproved.
        /// </summary>
        public static string DISAPPROVED {
            get {
                return ResourceManager.GetString("DISAPPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alert.
        /// </summary>
        public static string EMAIL_ALERT {
            get {
                return ResourceManager.GetString("EMAIL_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter rejection reason.
        /// </summary>
        public static string ENTER_REJECTION_REASON {
            get {
                return ResourceManager.GetString("ENTER_REJECTION_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MOBILE_NUMBER {
            get {
                return ResourceManager.GetString("MOBILE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string PENDING {
            get {
                return ResourceManager.GetString("PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection Reason.
        /// </summary>
        public static string REJECTION_REASON {
            get {
                return ResourceManager.GetString("REJECTION_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Alert.
        /// </summary>
        public static string SMS_ALERT {
            get {
                return ResourceManager.GetString("SMS_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNO.
        /// </summary>
        public static string SNO {
            get {
                return ResourceManager.GetString("SNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Approved.
        /// </summary>
        public static string UPDATE_APPROVED {
            get {
                return ResourceManager.GetString("UPDATE_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update DisApproved.
        /// </summary>
        public static string UPDATE_DISAPPROVED {
            get {
                return ResourceManager.GetString("UPDATE_DISAPPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Pending.
        /// </summary>
        public static string UPDATE_PENDING {
            get {
                return ResourceManager.GetString("UPDATE_PENDING", resourceCulture);
            }
        }
    }
}
