//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertProfiler.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlertProfiler.WebApp.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN DASHBOARD.
        /// </summary>
        public static string ADMIN_DASHBOARD {
            get {
                return ResourceManager.GetString("ADMIN_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALERT DASHBOARD.
        /// </summary>
        public static string ALERT_DASHBOARD {
            get {
                return ResourceManager.GetString("ALERT_DASHBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finacle Alert Report.
        /// </summary>
        public static string ALERT_FINACLE_REPORT {
            get {
                return ResourceManager.GetString("ALERT_FINACLE_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Report.
        /// </summary>
        public static string ALERT_REPORT_MENU {
            get {
                return ResourceManager.GetString("ALERT_REPORT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        public static string AUDIT_MENU {
            get {
                return ResourceManager.GetString("AUDIT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LOG_OUT {
            get {
                return ResourceManager.GetString("LOG_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Subscriber(Alert).
        /// </summary>
        public static string MANAGE_SUSCRIBER_MENU {
            get {
                return ResourceManager.GetString("MANAGE_SUSCRIBER_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suscribe Alert.
        /// </summary>
        public static string SUSCRIBE_ALERT_MENU {
            get {
                return ResourceManager.GetString("SUSCRIBE_ALERT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Alert Profile.
        /// </summary>
        public static string UPDATE_ALERT_MENU {
            get {
                return ResourceManager.GetString("UPDATE_ALERT_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WELCOME_MESSAGE {
            get {
                return ResourceManager.GetString("WELCOME_MESSAGE", resourceCulture);
            }
        }
    }
}
