//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlertProfiler.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SuscribeAlert {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuscribeAlert() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlertProfiler.WebApp.Resources.SuscribeAlert", typeof(SuscribeAlert).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string ACCOUNT_NAME {
            get {
                return ResourceManager.GetString("ACCOUNT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string ACCOUNT_NUMBER {
            get {
                return ResourceManager.GetString("ACCOUNT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string ACCOUNT_TYPE {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BACK_BTN_VALUE {
            get {
                return ResourceManager.GetString("BACK_BTN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alerts.
        /// </summary>
        public static string EMAIL_ALERTS {
            get {
                return ResourceManager.GetString("EMAIL_ALERTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter account number.
        /// </summary>
        public static string ENTER_ACCOUNT_NUMBER {
            get {
                return ResourceManager.GetString("ENTER_ACCOUNT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Profile Detail(s).
        /// </summary>
        public static string EXISTING_PROFILER {
            get {
                return ResourceManager.GetString("EXISTING_PROFILER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string LOAD_ACCOUNTS {
            get {
                return ResourceManager.GetString("LOAD_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MESSAGE {
            get {
                return ResourceManager.GetString("MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Alerts.
        /// </summary>
        public static string MOBILE_ALERTS {
            get {
                return ResourceManager.GetString("MOBILE_ALERTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:  Kindly advise the customer to fill an account update form to update his / her account information..
        /// </summary>
        public static string NO_ACCOUNT_MESSAGE {
            get {
                return ResourceManager.GetString("NO_ACCOUNT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SUBMIT_BTN_VALUE {
            get {
                return ResourceManager.GetString("SUBMIT_BTN_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tick alert options below.
        /// </summary>
        public static string TICK_OPTIONS {
            get {
                return ResourceManager.GetString("TICK_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Alert below.
        /// </summary>
        public static string UPDATE_ALERT_BELOW {
            get {
                return ResourceManager.GetString("UPDATE_ALERT_BELOW", resourceCulture);
            }
        }
    }
}
